from: markdown

resource-path:
  - "${.}/../"
  - "${.}/../filters/wenkokke/bubble/"

filters:
  # Enable Bubble filter
  - "${.}/../filters/wenkokke/bubble/bubble.lua"

metadata:
  author: "Keri Kokke"
  author-meta: "Keri Kokke"
  lang: "en-GB"

  # Configuration for Bubble filter
  bubble:
    blockquote: "true"
    Sam:
      style: "bottom-left"
    Cat:
      style: "bottom-right"
